### PR TITLE
Add ability to handle exception in fail callback

### PR DESCRIPTION
**Pull request by groony**
For better handling exception, added attribute exception.

### CODE REVIEW

**Comment by groony** [comment]
any questions?)

**Comment by piton4eg** [comment]
Could you describe a case when we need this feature?

**Comment by piton4eg** [comment]
Sorry for delay

**Comment by groony** [comment]
@piton4eg 
When i use some external api in block with AR, and if request failed i need to specify error message from exception.

**Comment by kimrgrey** [comment]
Merged and released as 0.9.0. Thanks for the contribution 👍

**Pull request merged**
